version: '3.1'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - "./html:/var/www/html"
    ports:
      - "8080:80"
    links:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    restart: always
    volumes:
      - "./html:/var/www/html"
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret